In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("iris.csv", index_col=0, na_values=(["??", "????", "###"]))

In [3]:
data["Species"].replace('Iris-setosa', 1, inplace=True)
data["Species"].replace('Iris-versicolor', 2, inplace=True)
data["Species"].replace('Iris-virginica', 3, inplace=True)

In [4]:
data["Species"]=data["Species"].astype("int64")

In [5]:
class_label=np.array(['Iris-sentosa', 'Iris-versicolor', 'Iris-virginica'])

In [6]:
data['SepalLengthCm'].fillna(data['SepalLengthCm'].mean(), inplace=True)
data['SepalWidthCm'].fillna(data['SepalWidthCm'].mean(), inplace=True)
data['PetalLengthCm'].fillna(data['PetalLengthCm'].mean(), inplace=True)
data['PetalWidthCm'].fillna(data['PetalWidthCm'].mean(), inplace=True)

In [7]:
column_list=list(data.columns)
feature_list=list(set(data.columns)-set(data['Species']))
X=data[feature_list].values
Y=data["Species"].values

In [8]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y=train_test_split(X, Y, test_size=0.25, random_state=None)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()
classifier.fit(train_x, train_y)
y_dash=classifier.predict(test_x)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm5=confusion_matrix(test_y, y_dash)
acc5=accuracy_score(test_y, y_dash)
print("The confusion matrix is: \n", cm5)
print("The accuracy score is: ", acc5*100)
print("Misclassified samples = {}".format((test_y != y_dash).sum()))

The confusion matrix is: 
 [[ 7  0  0]
 [ 0 19  0]
 [ 0  0 12]]
The accuracy score is:  100.0
Misclassified samples = 0
