In [4]:
import pandas as pd
import numpy as np

In [5]:
def calculate_prob(x,mean,variance):
    exponent = np.exp(-((x-mean)**2/(2*variance)))
    return (1/(np.sqrt(2*np.pi)*variance))*exponent

In [6]:
data = pd.read_csv("iris.csv",index_col=0,na_values=['??','???','###'])
print(np.unique(data['SepalLengthCm']))
print(np.unique(data['SepalWidthCm']))
print(np.unique(data['PetalLengthCm']))
print(np.unique(data['PetalWidthCm']))
print(np.unique(data['Species']))

[4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.
 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6 7.7 7.9 nan]
[2.  2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.4 nan]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.9 3.  3.3 3.5 3.6 3.7 3.8 3.9 4.  4.1
 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9
 6.  6.1 6.3 6.4 6.6 6.7 6.9 nan]
[0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1
 2.2 2.3 2.4 2.5]
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [7]:
data['Species'].replace('Iris-setosa',1,inplace=True)
data['Species'].replace('Iris-versicolor',2,inplace=True)
data['Species'].replace('Iris-virginica',3,inplace=True)
data['Species']=data['Species'].astype('int64')

In [8]:
data['SepalLengthCm'].fillna(data['SepalLengthCm'].mean(),inplace=True)
data['SepalWidthCm'].fillna(data['SepalWidthCm'].mean(),inplace=True)
data['PetalLengthCm'].fillna(data['PetalLengthCm'].mean(),inplace=True)

In [22]:
class_label = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
features = np.array(['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'])

In [23]:
AM = np.zeros((len(features),len(class_label)))
AV = np.zeros((len(features),len(class_label)))

In [24]:
for i in range(len(class_label)):
    clas = pd.DataFrame(data[data['Species'].isin([i+1])])
    for j in range(len(features)):
        AM[j][i] = np.mean(clas[features[j]])
        AV[j][i] = np.var(clas[features[j]])

In [25]:
print("ENTER INPUTS:")
SL = float(input("Enter the SepalLength: "))
SW = float(input("Enter the SepalWidth: "))
PL = float(input("Enter the PetalLength: "))
PW = float(input("Enter the PetalWidth: "))
x = [SL,SW,PL,PW]
A = np.zeros((len(features),len(class_label)))

ENTER INPUTS:
Enter the SepalLength: 5
Enter the SepalWidth: 3
Enter the PetalLength: 5
Enter the PetalWidth: 2


In [26]:
for i in range(len(features)):
    A[i] = calculate_prob(x[i],AM[i],AV[i])
print(A)

[[3.00801467e+00 2.85424316e-01 4.17854579e-02]
 [1.51604179e+00 3.14300853e+00 3.90115675e+00]
 [2.07808648e-11 5.20189901e-01 8.02247122e-01]
 [1.27306848e-58 2.77632588e-02 5.37203581e+00]]


In [27]:
large = 0.0
pc = np.array([0.33,0.33,0.33])
for i in range(len(class_label)):
    for j in range(len(features)):
        pc[i] = pc[i]*A[j][i]
    if large < pc[i]:
        large = pc[i]
        k = i
print(pc)
print(class_label[k])

[3.98125913e-69 4.27545980e-03 2.31835305e-01]
Iris-virginica
