In [1]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("iris.csv", index_col=0, na_values=(["??", "????", "###"]))
print(data)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           NaN            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              NaN           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            NaN           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]


In [4]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  149 non-null    float64
 1   SepalWidthCm   149 non-null    float64
 2   PetalLengthCm  148 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 7.0+ KB
None


In [6]:
print(np.unique(data["SepalLengthCm"]))
print(np.unique(data["SepalWidthCm"]))
print(np.unique(data["PetalLengthCm"]))
print(np.unique(data["PetalWidthCm"]))
print(np.unique(data["Species"]))

[4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.
 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6 7.7 7.9 nan]
[2.  2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.4 nan]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.9 3.  3.3 3.5 3.6 3.7 3.8 3.9 4.  4.1
 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9
 6.  6.1 6.3 6.4 6.6 6.7 6.9 nan]
[0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1
 2.2 2.3 2.4 2.5]
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [7]:
data["Species"].replace('Iris-setosa', 1, inplace=True)
data["Species"].replace('Iris-versicolor', 2, inplace=True)
data["Species"].replace('Iris-virginica', 3, inplace=True)

In [8]:
class_label=np.array(['Iris-sentosa', 'Iris-versicolor', 'Iris-virginica'])

In [9]:
print(data.isnull().sum())
data['SepalLengthCm'].fillna(data['SepalLengthCm'].mean(), inplace=True)
data['SepalWidthCm'].fillna(data['SepalWidthCm'].mean(), inplace=True)
data['PetalLengthCm'].fillna(data['PetalLengthCm'].mean(), inplace=True)

SepalLengthCm    1
SepalWidthCm     1
PetalLengthCm    2
PetalWidthCm     0
Species          0
dtype: int64


In [10]:
column_list=list(data.columns)
feature_list=list(set(data.columns)-set(data['Species']))
X=data[feature_list].values
Y=data["Species"].values

In [11]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y=train_test_split(X, Y, test_size=0.25, random_state=0)

In [12]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(train_x, train_y) #Model training
y_dash=classifier.predict(test_x) #Model testing

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(test_y, y_dash)
acc=accuracy_score(test_y, y_dash)
print(cm)
print(acc*100)

[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
100.0
